apiVersion: skaffold/v2alpha1
kind: Config
metadata:
  name: jakartaee8-java11
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: lreimer/jakartaee8-java11
    jib: {}
deploy:
  kubectl:
    manifests:
    - kubernetes/microservice.yaml
portForward:
  - resourceType: service
    resourceName: jakartaee8-java11
    namespace: default
    port: 8080
    localPort: 8080
profiles:
  - name: development
    activation:
      - kubeContext: docker-desktop
