apiVersion: v1
kind: Service
metadata:
  name: jakartaee8-java11
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: jakartaee8-java11
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jakartaee8-java11
  labels:
    app: jakartaee8-java11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jakartaee8-java11
  template:
    metadata:
      labels:
        app: jakartaee8-java11
    spec:
      containers:
        - name: jakartaee8-java11
          image: jakartaee8-java11
          ports:
            - containerPort: 8080
